New tests; tighter code and comments

diff --git a/tests/pmaptrap b/tests/pmaptrap
--- a/tests/pmaptrap
+++ b/tests/pmaptrap
@@ -12,13 +12,14 @@
 THREADS=ALL	# a number, or ALL, threads on each node
 
 ###########################################################################
-# Process command line, set scope of some globals
+# Process command line, set scalar globals.
 
 DEVNULL='> /dev/null 2>&1'
 [ "$1" = "-v" ] && QUIET="" || QUIET="$DEVNULL"
 
 set -u
 
+BIGFILE=/lfs/bigfile
 PSSHOSTS=$HOME/hosts.pssh
 shopt -s expand_aliases
 alias pssh="parallel-ssh -i -h $PSSHOSTS -l l4tm -t 0"
@@ -26,16 +27,16 @@ alias pssh="parallel-ssh -i -h $PSSHOSTS -l l4tm -t 0"
 TMHOSTS=`jq -r '.racks[].enclosures[].nodes[].soc.hostname' < /etc/tmconfig`
 # echo $TMHOSTS
 
-declare -ag HOSTNAMES NODE_IDS
-
 ###########################################################################
 
 function trace() {
-    [ "$QUIET" ] || echo -e "\n-------------- $*\n"
+    [ "$QUIET" ] || echo -e "\n------ $*\n"
 }
 
 ###########################################################################
-# Give values to the globally scoped variables.
+# Give values to globally-scoped arrays.
+
+declare -ag HOSTNAMES NODE_IDS
 
 function set_globals() {
     trace "Set globals"
@@ -49,18 +50,55 @@ function set_globals() {
     # echo ${HOSTNAMES[*]}
     echo ${HOSTNAMES[*]} | tr ' ' '\n' > $PSSHOSTS
 
-    # Not really using this, but don't waste it
+    # Assumes hostnames are of the form "nodeXX"
     NODE_IDS=()
     for H in ${HOSTNAMES[*]}; do
 	NODE_IDS+=(${H:4:2})
     done
     echo "Active nodes: ${NODE_IDS[*]}"
 
-    # Can I hit them all?  Usually an ssh config problem
+    # Can I hit them all?  If not, it's usually an ssh config problem
+    # but may be a mismatch between /etc/tmconfig and reality.
     eval pssh echo $QUIET
     [ $? -ne 0 ] && echo "pssh echo failed" >&2 && exit 1	# Yes, fatal
 
     return 0
+}
+
+###########################################################################
+# Can't really run on nodes booted "nosmp".
+
+function verify_boottype() {
+	NOSMP=0
+	for H in ${HOSTNAMES[*]}; do
+		ssh $H grep -q nosmp /proc/cmdline
+		let RET=1-$?
+		let NOSMP+=$RET
+		[ $RET -ne 0 ] && echo $H is running nosmp >&2
+	done
+	[ $NOSMP -gt 0 ] && echo "Re-bind and reboot those nodes" >&2 && exit 1
+	return 0
+}
+
+###########################################################################
+# If there are other files, this won't go to zero.  If "fake_zero" is not
+# set in the Librarian, this may take a while to go to zero.
+
+function remove_pmaptrap_files()
+{
+	# Kill the current file as it now has a private policy.
+	eval pssh rm -f '/lfs/\`hostname\`' $DEVNULL
+	[ $? -ne 0 ] && echo "pssh rm failed" >&2 && return 1
+
+	ssh $HOSTNAMES rm -f $BIGFILE	# no subscript == first one
+
+	NFILES=`ssh $HOSTNAMES ls -a /lfs | wc -l`
+	while [ $NFILES -gt 2 ]; do
+		echo "Waiting for files on /lfs to clear"
+		sleep 5
+		NFILES=`ssh $HOSTNAMES ls -a /lfs | wc -l`
+	done
+	return 0
 }
 
 ###########################################################################
@@ -83,9 +121,7 @@ function allocate_pernode_files() {
 	POLICY=$1
 	SIZE=$2
 
-	# Kill the previous file, as it now has a private policy.
-	eval pssh rm -f '/lfs/\`hostname\`' $DEVNULL
-	[ $? -ne 0 ] && echo "pssh rm failed" >&2 && return 1
+	remove_pmaptrap_files
 
 	parallel_policy $POLICY
 	[ $? -ne 0 ] && return 1
@@ -100,23 +136,64 @@ function allocate_pernode_files() {
 }
 
 ###########################################################################
-# Standard maptrap options are passed in, filename is calculated.  See
-# comments in allocate_pernode_files() about the funky backslashes.
+# Standard maptrap options are passed in.  If the final argument is not an
+# existing file, calculate the filename.  See comments in 
+# allocate_pernode_files() about the funky backslashes.  Failures are fatal.
 
 function parallel_maptrap() {
 	MSG="$1"
-	trace "$MSG"
 	shift
-	ARGS=$*
+	declare -a TMP=($*)
+	FNAME=${TMP[-1]}
+	ARGS="${TMP[*]}"
 	eval pssh sudo killall -9 maptrap $DEVNULL
-	[ "$QUIET" ] && echo -n "$MSG (maptrap $ARGS /lfs/nodeXX)..."
-	eval pssh /srv/rocky/maptrap $ARGS '/lfs/\`hostname\`' $QUIET
+	ssh $HOSTNAMES ls $FNAME $DEVNULL
+	test $? -eq 0 -a ${FNAME:0:1} = '/'
+	if [ $? -eq 0 ]; then
+		trace "$MSG ($ARGS)"
+		[ "$QUIET" ] && echo -n "$MSG ($ARGS)"
+		eval pssh /srv/rocky/maptrap $ARGS $QUIET
+	else
+		trace "$MSG ($ARGS /lfs/nodeXX)"
+		[ "$QUIET" ] && echo -n "$MSG ($ARGS /lfs/nodeXX)..."
+		eval pssh /srv/rocky/maptrap $ARGS '/lfs/\`hostname\`' $QUIET
+	fi
 	if [ $? -ne 0 ]; then
 		[ "$QUIET" ] && echo "FAILED"
-		return 1
+		exit 1
 	fi
 	[ "$QUIET" ] && echo "passed"
 	return 0
+}
+
+###########################################################################
+#  Have every file live on one node.  At 128G NVM DIMMs, max of 3 books.
+
+function allocate_one_node_files() {
+    let IG=$1-1
+    IG=`printf "0x%02X" $IG`
+
+    remove_pmaptrap_files
+
+    for H in HOSTNAMES; do
+	eval pssh touch '/lfs/\`hostname\`' $DEVNULL
+	[ $? -ne 0 ] && echo "pssh touch failed" >&2 && return 1
+    	
+	eval pssh setfattr -n user.LFS.AllocationPolicy -v RequestIG \
+		'/lfs/\`hostname\`' $DEVNULL
+	[ $? -ne 0 ] && echo "pssh setfattr RequestIG failed" >&2 && return 1
+
+	eval pssh setfattr -n user.LFS.InterleaveRequest -v $IG \
+		'/lfs/\`hostname\`' $DEVNULL
+	[ $? -ne 0 ] && echo "pssh setfattr IG request $IG failed" >&2 && return 1
+
+	SIZE=24G
+	eval pssh truncate -s $SIZE '/lfs/\`hostname\`' $DEVNULL
+	[ $? -ne 0 ] && echo "pssh truncate $SIZE failed" >&2 && return 1
+
+    done
+
+    return 0
 }
 
 ###########################################################################
@@ -132,37 +209,23 @@ function hispeed() {
 
 	# Shawn Walker likes it, but it's not useful here.
 	# parallel_maptrap "HiSpeed fixed read $POLICY" -H1 -L$LIMIT -T $THREADS
-	# [ $? -ne 0 ] && exit 1
 
 	parallel_maptrap "HiSpeed random read $POLICY" -H2 -L$LIMIT -T $THREADS
-	[ $? -ne 0 ] && exit 1
 
 	parallel_maptrap "HiSpeed random R-M-W $POLICY" -H3 -L$LIMIT -T $THREADS
-	[ $? -ne 0 ] && exit 1
 	return 0
 }
 
 ###########################################################################
-# Can't really run on nodes booted with "nosmp"
-
-function verify_boottype() {
-	NOSMP=0
-	for H in ${HOSTNAMES[*]}; do
-		ssh $H grep -q nosmp /proc/cmdline
-		let RET=1-$?
-		let NOSMP+=$RET
-		[ $RET -ne 0 ] && echo $H is running nosmp >&2
-	done
-	[ $NOSMP -gt 0 ] && echo "Re-bind and reboot those nodes" >&2 && exit 1
-	return 0
-}
-
-###########################################################################
-# MAIN
+# MAIN.  Begin with setup/cleanup.
 
 set_globals
 
 verify_boottype
+
+eval pssh sudo killall -9 maptrap $DEVNULL
+
+remove_pmaptrap_files
 
 #--------------------------------------------------------------------------
 # Canned tests that haven't failed in a while.
@@ -170,19 +233,37 @@ verify_boottype
 # per node).  We believe is the data on each node is subject to local 
 # processing, the precept of memory-centric computing.
 
-hispeed LocalNode 30
+hispeed LocalNode 60
 
-hispeed NearestRemote 30	# should stay inTRA-enclosure, not inTER
+hispeed NearestRemote 60	# should stay inTRA-enclosure, not inTER
 
 #--------------------------------------------------------------------------
 # 200G is 20% of a node's NVM with 32G DIMMs, aka 24 books.
 # Open it up.  With forty nodes and many books in each node's file, lots
 # of intra-node, intra-enclosure, and inter-enclosure traffic will ensue.
 
-allocate_pernode_files RandomBooks 200G
-[ $? -ne 0 ] && exit 1
+allocate_pernode_files RandomBooks 300G
 
-parallel_maptrap "Full random R-M-W" -qSRW -L30 -T $THREADS
-[ $? -ne 0 ] && exit 1
+parallel_maptrap "Full random R-M-W" -qSRWj -L300 -T $THREADS
+
+#--------------------------------------------------------------------------
+# Have one node host all the per-node files.  Give them all a chance.
+
+for ID in ${NODE_IDS[*]}; do
+	allocate_one_node_files $ID
+	[ $? -ne 0 ] && exit 1
+	parallel_maptrap "Full random R-M-W, files on node$ID" -qSRWj -L600 -T $THREADS
+done
+
+#--------------------------------------------------------------------------
+# Have one large file accessed by all nodes: probably what LSGi really does.
+
+remove_pmaptrap_files
+
+parallel_policy RandomBooks
+
+ssh $HOSTNAMES truncate -s 500G $BIGFILE
+
+parallel_maptrap "Full random R-M-W to $BIGFILE" -qSRWj -L600 -T $THREADS $BIGFILE
 
 exit 0
